name: Redundancy check
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Automatic deploy"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Install dependencies
        run: npm install
      - name: Run redundancy check script
        run: node check.js
